name: CI/CD for Demo App 

on:  
  push:  
    branches:  
      - main  

jobs:  
  update-deployment:  
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Update Docker Image Tag  
        run: |  
          sed -i 's@image: nguyentrachminh/demo-web-app:.*@image: nguyentrachminh/demo-web-app:${{ github.sha }}@g' demo-app-deployment.yaml  
        # Script để cập nhật tệp Kubernetes với tag hình ảnh mới 
      - name: Commit and Push changes  
        run: |  
          git config --local user.email "nguyentrachminh@gmail.com"  
          git config --local user.name "nguyentrachminh"  
          git add demo-app-deployment.yaml 
          git commit -m "Update deployment with new Docker image"  
          git push
