name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger CI/CD khi có thay đổi trên nhánh 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          nguyentrachminh/demo-web-app:latest
          nguyentrachminh/demo-web-app:${{ github.sha }}

    - name: Commit updated image to GitHub
      run: |
        git config --global user.email "nguyentrachminh@gmail.com"
        git config --global user.name "nguyentrachminh"
        git checkout main
        sed -i 's@image: nguyentrachminh/demo-web-app:.*@image: nguyentrachminh/demo-web-app:${{ github.sha }}@g' demo-web-app/demo-app-deployment.yaml
        git add demo-web-app/demo-app-deployment.yaml
        git commit -m "Update deployment to image ${{ github.sha }}"
        git push
