name: CI/CD for Demo App Web

on:
  push:
    branches:
      - main  # Thay đổi khi có bất kỳ commit nào lên nhánh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Được cấu hình trong GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Được cấu hình trong GitHub Secrets

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: nguyentrachminh/demo-app-web:latest

    - name: Notify ArgoCD of new deployment
      run: kubectl rollout restart deployment/demo-app
