name: CI/CD Pipeline  

on:  
  push:  
    branches:  
      - main  
    paths:  
      - 'index.html'  # Theo dõi các thay đổi đối với file index.html  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Set up Docker Buildx  
        uses: docker/setup-buildx-action@v1  

      - name: Log in to Docker Hub  
        uses: docker/login-action@v1  
        with:  
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build Docker image  
        run: |  
          docker build -t nguyentrachminh/demo-web-app:latest .  
          
      - name: Push Docker image  
        run: |  
          docker push nguyentrachminh/demo-web-app:latest  

      - name: Update ArgoCD deployment file  
        run: |  
          sed -i 's#image: nguyentrachminh/demo-web-app:.*#image: nguyentrachminh/demo-web-app:latest#' demo-app-deployment.yaml  

      - name: Commit and push updated ArgoCD deployment file  
        run: |  
          git config --local user.email "nguyentrachminh@gmail.com"  
          git config --local user.name "Minhyoyo"  
          git add demo-app-deployment.yaml  
          git commit -m "Update deployment with new Docker image"  
          git push origin main  
        env:  
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
